name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: FTP Deploy Locaweb
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ftp.nelson-proenca-info.com.br
        user: nelson-proenca-i1
        password: sW!MJ4F#yki!GMP
        localDir: "dist"
